name: Build release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout a specific file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            main.py
          sparse-checkout-cone-mode: false

      - name: Install pyinstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile main.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Linux
          path: dist/main

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout a specific file
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            main.py
          sparse-checkout-cone-mode: false

      - name: Install pyinstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile main.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Linux
          path: dist/main
          compression-level: 9
