name: Build release

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout a specific file
        uses: actions/checkout@v4

      - name: Set version tag
        id: version
        run: |
          TAG_NAME="v$(date +%Y.%m.%d-%H%M)"  # Generates a tag like 'v2025.02.16-1430'
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
      
      - name: Install pyinstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile main.py

      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_COMPRESS: xz
          GHR_PATH: dist/main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.TAG_NAME }}  # Uses the auto-generated tag
